const icons={

    LogoFulll:require('../icons/mylogo_full.png'),
    LogoFulllGif:require('../icons/mylogo_fullGif.gif'),
    Loading:require('../icons/loading.gif'),
    Phone:require('../icons/phone.png'),
    EyeOpen:require('../icons/eye_open.png'),
    EyeClose:require('../icons/eye_close.png'),
    Password:require('../icons/password.png'),
    User:require('../icons/user.png'),
    User2:require('../icons/user2.png'),
    Identity:require('../icons/identity.png'),
    Identity2:require('../icons/identity2.png'),
    Mail:require('../icons/mail.png'),
    Google:require('../icons/google.png'),
    Facebook:require('../icons/facebook.png'),
    FakeBackground:require('../icons/background.jpg'),
    Galery:require('../icons/galery.png'),
    Help:require('../icons/help.png'),
    Maps:require('../icons/maps.png'),
    About:require('../icons/about.png'),

    Coffie:require('../icons/coffie.png'),
    Tarot:require('../icons/tarot.png'),
    Katina:require('../icons/katina.png'),
    Hand:require('../icons/hand.png'),
    Water:require('../icons/water.png'),
    Dream:require('../icons/dream.png'),
    Iskambil:require('../icons/iskambil.png'),
    Gift:require('../icons/gift.png'),
    Coin:require('../icons/coin.png'),
    Market:require('../icons/market.png'),
    Home:require('../icons/home.png'),
    Back:require('../icons/back.png'),
    Filter:require('../icons/filter.png'),
    Star:require('../icons/star.png'),
    Message:require('../icons/message.png'),
    Mic:require('../icons/mic.png'),
    Friends:require('../icons/friends.png'),
    Right:require('../icons/right.png'),
    Love:require('../icons/love.png'),
    Date:require('../icons/date.png'),
    Gender:require('../icons/gender.png'),
    Candle:require('../icons/candle.png'),
    Horoscope:require('../icons/horoscope.png'),
    Whatsapp:require('../icons/whatsapp.png'),
    Apple:require('../icons/apple.png'),
    CreditCard:require('../icons/credit_card.png'),
    History:require('../icons/history.png'),
    Search:require('../icons/search.png'),
    Plus:require('../icons/plus.png'),
    CartBack:require('../icons/cart_back.jpg'),
    KatinaBack:require('../icons/katina_back.png'),
    IskambilBack:require('../icons/iskambil_back.png'),
    Play:require('../icons/play.png'),
    Pause:require('../icons/pause.png'),
    Stop:require('../icons/stop.png'),
    Rate:require('../icons/rate.png'),
    Sector:require('../icons/sector.png'),
    Save:require('../icons/save.png'),
    Office:require('../icons/office.png'),
    Add:require('../icons/add.png'),
    Info:require('../icons/info.png'),
    CheckMar:require('../icons/checkmar.png'),
    Error:require('../icons/error.png'),



    IMAGE1:require('../icons/image1.jpeg'),
    IMAGE2:require('../icons/image2.jpeg'),
    IMAGE3:require('../icons/image3.jpeg'),
    IMAGE4:require('../icons/image4.jpeg'),
    IMAGE5:require('../icons/image5.jpeg'),
    IMAGE6:require('../icons/image6.jpeg'),
    IMAGE7:require('../icons/image7.jpeg'),
    IMAGE8:require('../icons/image8.jpeg'),


}

export default icons